Update README.md
kbsali/php-redmine-api pull request #250
Opened 2020-10-11 09:50 UTC by ratan325

usr == user
php == PHP
phpunit = PHPUnit

2020-12-30 11:34 UTC, Art4 requested changes
I'm not a native english speaker, but some technical changes looks like a search/replace without understanding the meanings.

2020-12-30 11:34 UTC, Art4 commented on README.md
> +a project or globally; say, in `/user/share/PHP`.
:-1:  this is not a typical path.

2020-12-30 11:34 UTC, Art4 commented on README.md
> +`vendor/PHP-Redmine-API-1.5.18` directory:
:-1:

2020-12-30 11:34 UTC, Art4 commented on README.md
> +You can run the test suite to make sure the library will work properly on your system. Simply run `vendor/bin/PHPUnit` in the project's directory :
:-1: 
this path would be invalid.

2020-12-30 11:34 UTC, Art4 commented on README.md
> +$ vendor/bin/PHPUnit
:-1:  same here.

2020-12-30 11:34 UTC, Art4 commented on README.md
> +PHP
:-1: 
this line marks a code area with PHP syntax highlighting. This change makes no sense.

2020-12-30 11:34 UTC, Art4 commented on README.md
> +* Thanks to [Thibault Duplessis aka. ornicar](https://github.com/ornicar) for the PHP-GitHub-API library, a great source of inspiration!
:-1: 
The name of the library is "php-github-api" , see https://github.com/ornicar/php-github-api

2021-01-02 10:20 UTC, kbsali commented
@Art4 this is the typical useless PR that propagated on github during the hacktober fest!
Theses guys (@ratan325 and others) went on creating shitty pull request to get... a t-shirt! Ridiculous!

2021-01-02 10:20 UTC, closed without merging

2021-01-02 11:31 UTC, Art4 commented
Oh, I see... :facepalm: