Fix $lastResponseContentType of type string
kbsali/php-redmine-api pull request #291
Opened 2021-07-02 03:52 UTC by phungthuan99

Fatal error: Uncaught TypeError: Cannot assign int to property Redmine\Client\NativeCurlClient::$lastResponseContentType of type string in D:\xampp-v8\htdocs\wordpress\wp-content\plugins\wordpress-cloodo-plugins\libs\Redmine\Client\NativeCurlClient.php:235 Stack trace: #0 D:\xampp-v8\htdocs\wordpress\wp-content\plugins\wordpress-cloodo-plugins\libs\Redmine\Client\NativeCurlClient.php(81): Redmine\Client\NativeCurlClient->request('get', '/users/current....') #1 D:\xampp-v8\htdocs\wordpress\wp-content\plugins\wordpress-cloodo-plugins\libs\Redmine\Api\AbstractApi.php(49): Redmine\Client\NativeCurlClient->requestGet('/users/current....') #2 D:\xampp-v8\htdocs\wordpress\wp-content\plugins\wordpress-cloodo-plugins\libs\Redmine\Api\User.php(121): Redmine\Api\AbstractApi->get('/users/current....') #3 D:\xampp-v8\htdocs\wordpress\wp-content\plugins\wordpress-cloodo-plugins\libs\Redmine\Api\User.php(66): Redmine\Api\User->show('current', Array) #4 D:\xampp-v8\htdocs\wordpress\wp-content\plugins\wordpress-cloodo-plugins\cloodo.php(27): Redmine\Api\User->getCurrentUser(Array) #5 D:\xampp-v8\htdocs\wordpress\wp-settings.php(391): include_once('D:\\xampp-v8\\htd...') #6 D:\xampp-v8\htdocs\wordpress\wp-config.php(90): require_once('D:\\xampp-v8\\htd...') #7 D:\xampp-v8\htdocs\wordpress\wp-load.php(37): require_once('D:\\xampp-v8\\htd...') #8 D:\xampp-v8\htdocs\wordpress\wp-admin\admin.php(34): require_once('D:\\xampp-v8\\htd...') #9 {main} thrown in D:\xampp-v8\htdocs\wordpress\wp-content\plugins\wordpress-cloodo-plugins\libs\Redmine\Client\NativeCurlClient.php on line 235

2021-07-05 07:53 UTC, Art4 commented
Hello and thank you very much for your contribution.

I would like to harden this change with some tests.

Can I ask you to provide more context about this issue? Can you provide some code example? Which curl options have you set that `curl_getinfo` returns an integer?

2021-07-05 11:35 UTC, Art4 requested changes
We need more data about the circumstances to create tests for this behavior.

2021-07-21 14:07 UTC, rvanlande commented
Hello !

I have the same problem :

```
typed property Redmine\Client\NativeCurlClient::$lastResponseContentType must be string, bool used
lib/vendor/kbsali/redmine-api/src/Redmine/Client/NativeCurlClient.php::235
```

My test :

php : 7.4.21
redmine: i am not sure about version because i am not the administrator, i think 4.x
redmine-php-api : 1.8.1

```
...
$client = new \Redmine\Client\NativeCurlClient($url, $key);
$client->getApi('issue')->update($issueId, [
  'id' => $issueId,
  'status_id' => $status_id,
]);
```

`curl_getinfo($curl, CURLINFO_CONTENT_TYPE)` return false, when we expect a string
In my test case, the line before  `curl_getinfo($curl, CURLINFO_HTTP_CODE)` returns code 204

Thanks for your work.

2021-09-20 15:03 UTC, kbsali commented
@Art4 shouldn't we merge that one? :)

2021-09-20 15:28 UTC, Art4 commented
> @Art4 shouldn't we merge that one? (after fixing the CS :))

Unfortunately, I have not yet found time to reproduce the error and write a test for it.

2021-09-20 18:28 UTC, kbsali commented
i think the risk that it might break something is very low :)

2021-09-22 07:11 UTC, Art4 commented
I've created a test for handling a missing content type in a response. What surprises me is the return of `int` or `bool` of `curl_getinfo($curl, CURLINFO_CONTENT_TYPE)`. The docu says that NULL will be returned if the server did not send a valid content type header.

https://www.php.net/manual/en/function.curl-getinfo.php

> CURLINFO_CONTENT_TYPE - Content-Type: of the requested document. NULL indicates server did not send valid Content-Type: header

But this PR will fix the problem.

2021-09-22 07:13 UTC, Art4 approved these changes

2021-09-22 07:18 UTC, Art4 commented
@kbsali From my side this PR is ready for merge. After merge I will release v2.0.1

2021-09-22 07:35 UTC, merged

2021-09-22 07:35 UTC, kbsali commented
thanks @phungthuan99 and @Art4 :1st_place_medal:

2021-09-22 08:10 UTC, Art4 commented
I've release v2.0.1. Please make sure to upgrade to `^2.0` if you are still using v1 to get this bugfix.