chore: add Artur to the list of package authors
kbsali/php-redmine-api pull request #323
Opened 2023-09-20 11:53 UTC by kbsali

2023-09-20 13:10 UTC, Art4 requested changes
Thank you. 😊

2023-09-20 13:10 UTC, Art4 commented on composer.json
> +            "homepage": "http://kevin.saliou.name"
```suggestion
            "homepage": "https://wlabs.de"
```

2023-09-20 13:13 UTC, kbsali commented on composer.json
> +            "homepage": "http://kevin.saliou.name"
oops :sweat_smile:

2023-09-20 13:27 UTC, Art4 approved these changes

2023-09-20 13:47 UTC, kbsali commented
@Art4 I have tried to setup codecov but it fails at generating the coverage file... not sure how to fix this :pray:

2023-09-20 13:53 UTC, Art4 commented on .github/workflows/tests.yml
> +        run: vendor/bin/phpunit --coverage-clover coverage.xml .
```suggestion
        run: vendor/bin/phpunit --coverage-clover ./.code-coverage/clover.xml
```

2023-09-20 13:54 UTC, Art4 commented on .github/workflows/tests.yml
>            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```suggestion
      - name: Upload coverage reports to Codecov
        if: ${{ success() && matrix.matrix.php-versions == '8.2' }}
        uses: codecov/codecov-action@v3
        with:
          files: ./.code-coverage/clover.xml
          fail_ci_if_error: true
          verbose: true
```

2023-09-20 13:58 UTC, Art4 commented
> @Art4 I have tried to setup codecov but it fails at generating the coverage file... not sure how to fix this 🙏

I've made two suggestions to setup Codecov properly.

2023-09-20 13:59 UTC, Art4 requested changes
I've made two suggestions to setup Codecov properly.

2023-09-21 09:23 UTC, merged

2023-09-21 09:23 UTC, kbsali commented
:+1: